In [17]:
import os 
import fiona
import datetime
import seaborn as sns
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely import geometry
import matplotlib.pyplot as plt

In [71]:
# Create filepath for shapefile
fields_fp = "C:\\Users\\ashle\\Desktop\\KGS\\data\\Agriculture-Land\\Property Lines"
os.chdir(fields_fp)
fields = gpd.read_file('Fields_Around_SD6KS.shp')

In [72]:
# Create a filepath for OpenET data and change working directory
openET_fp = "C:\\Users\\ashle\\Desktop\\KGS\\data\\Hydrometeorology\\OpenET\\"
os.chdir(openET_fp)

In [85]:
# Import ensemble file from OpenET
ensemble = pd.read_csv('ET_monthly_ensemble_FieldsAroundSD6KS_20220708.csv')
# Import DisALEXI file from OpenET
disalexi = pd.read_csv('ET_monthly_disalexi_FieldsAroundSD6KS_20220708.csv')
# Import eeMetric file from OpenET
eemetric = pd.read_csv('ET_monthly_eemetric_FieldsAroundSD6KS_20220708.csv')
# Import geeSEBAL file from OpenET
geesebal = pd.read_csv('ET_monthly_geesebal_FieldsAroundSD6KS_20220708.csv')
# Import PT-JPL file from OpenET
ptjpl = pd.read_csv('ET_monthly_ptjpl_FieldsAroundSD6KS_20220708.csv')
# Import SIMS file from OpenET
sims = pd.read_csv('ET_monthly_sims_FieldsAroundSD6KS_20220708.csv')
# Import SSEBop file from OpenET
ssebop = pd.read_csv('ET_monthly_ssebop_FieldsAroundSD6KS_20220708.csv')

In [86]:
et = [ensemble, disalexi]
lab = ['annual_ensemble', 'annual_disalexi']
# , eemetric, geesebal, ptjpl, sims, ssebop

In [87]:
temp = []
annual_et = {}

In [88]:
for x in et:
    x.drop('acres', inplace=True, axis=1)
    merge_x = fields.merge(x, on='UID', how='left')
    x_fields = gpd.GeoDataFrame(merge_x)
    x_fields.time = pd.to_datetime(x_fields.time).dt.strftime('%Y')
    annual_x = x_fields.dissolve(by=['UID', 'time'], aggfunc='sum')
    annual_x.drop('area', inplace=True, axis=1)
    annual_x.reset_index(inplace=True).3

In [89]:
for i in range(len(temp)):
    annual_et[temp[i]] = lab[i]

TypeError: unhashable type: 'GeoDataFrame'

In [90]:
temp[0]

,UID,time,geometry,et_min,et_max,et_mean,et_median,et_sum
0,177799.0,2016,"POLYGON ((-414585.819 1818292.835, -415155.331...",454.0,1038.0,760.175,772.0,656067.018
1,177799.0,2017,"POLYGON ((-414585.819 1818292.835, -415155.331...",386.0,983.0,702.990,720.0,606713.032
2,177799.0,2018,"POLYGON ((-414585.819 1818292.835, -415155.331...",500.0,941.0,716.325,722.0,618222.393
3,177799.0,2019,"POLYGON ((-414585.819 1818292.835, -415155.331...",455.0,1023.0,698.216,699.0,602592.256
4,177799.0,2020,"POLYGON ((-414585.819 1818292.835, -415155.331...",559.0,987.0,775.223,777.0,669054.132
...,...,...,...,...,...,...,...,...
67879,1559412.0,2017,"POLYGON ((-396139.798 1849396.257, -396150.239...",576.0,980.0,815.310,799.0,219829.733
67880,1559412.0,2018,"POLYGON ((-396139.798 1849396.257, -396150.239...",571.0,1082.0,913.114,936.0,246200.521
67881,1559412.0,2019,"POLYGON ((-396139.798 1849396.257, -396150.239...",428.0,1090.0,741.545,738.0,199941.103
67882,1559412.0,2020,"POLYGON ((-396139.798 1849396.257, -396150.239...",654.0,1104.0,929.027,935.0,250491.401
67883,1559412.0,2021,"POLYGON ((-396139.798 1849396.257, -396150.239...",486.0,995.0,797.707,822.0,215083.880

0